version: "3.7"

services:
  builder:
    image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-dev-tools:latest
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - .:/app
    privileged: true
    environment:
      BOLOS_SDK: /opt/stax-secure-sdk
      DEBUG: 1
    command: make

  speculos:
    image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-dev-tools:latest
    depends_on:
      - builder
    volumes:
      - ./bin:/apps
      - $XDG_RUNTIME_DIR/$WAYLAND_DISPLAY:/tmp/$WAYLAND_DISPLAY
    environment:
      XDG_RUNTIME_DIR: /tmp
      WAYLAND_DISPLAY: $WAYLAND_DISPLAY
      QT_QPA_PLATFORM: wayland 
    ports:
      - "1234:1234" # gdb
      - "5000:5000" # api
      - "40000:40000" # apdu
      - "41000:41000" # vnc
    command: "speculos --model stax --apiLevel 15 --ontop /apps/app.elf"
