version: "3.7"

services:
  builder:
    image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder:latest
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - .:/app
    privileged: true
    environment:
      BOLOS_SDK: /opt/stax-secure-sdk
      DEBUG: 1
    command: make

  speculos:
    build:
      context: .
      dockerfile: Dockerfile.speculos
      network: host
    depends_on:
      - builder
    image: speculos:wordle
    volumes:
      - ./bin:/speculos/apps
      - /tmp/.X11-unix:/tmp/.X11-unix
      - "$HOME/.Xauthority:/root/.Xauthority:ro"
    environment:
      XDG_RUNTIME_DIR: /tmp
      DISPLAY: $DISPLAY
    ports:
      - "1234:1234" # gdb
      - "5000:5000" # api
      - "40000:40000" # apdu
      - "41000:41000" # vnc
    command: "--model stax --apiLevel 15 --ontop ./apps/app.elf "
